// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWyMtB67gQrk2ebkkwPlROZP5qh8rhYI',
    appId: '1:1079517476029:web:bc05d45aef3b8d5c9df3d4',
    messagingSenderId: '1079517476029',
    projectId: 'smartspendmap',
    authDomain: 'smartspendmap.firebaseapp.com',
    storageBucket: 'smartspendmap.appspot.com',
    measurementId: 'G-GQR4ZYX89J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFa17Bo06wzp_M-IY88WGX7oeLaqNUOCY',
    appId: '1:1079517476029:android:0a73015febdb9d6c9df3d4',
    messagingSenderId: '1079517476029',
    projectId: 'smartspendmap',
    storageBucket: 'smartspendmap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMLs2-AwyMFH7sGO5gyoKXzRfRbmlL0A',
    appId: '1:1079517476029:ios:1670830a1b6cfbfe9df3d4',
    messagingSenderId: '1079517476029',
    projectId: 'smartspendmap',
    storageBucket: 'smartspendmap.appspot.com',
    iosBundleId: 'com.example.budgetmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMLs2-AwyMFH7sGO5gyoKXzRfRbmlL0A',
    appId: '1:1079517476029:ios:1670830a1b6cfbfe9df3d4',
    messagingSenderId: '1079517476029',
    projectId: 'smartspendmap',
    storageBucket: 'smartspendmap.appspot.com',
    iosBundleId: 'com.example.budgetmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlWyMtB67gQrk2ebkkwPlROZP5qh8rhYI',
    appId: '1:1079517476029:web:c1e2b6d94c5a06ab9df3d4',
    messagingSenderId: '1079517476029',
    projectId: 'smartspendmap',
    authDomain: 'smartspendmap.firebaseapp.com',
    storageBucket: 'smartspendmap.appspot.com',
    measurementId: 'G-BS6PHCQSFB',
  );
}
